#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Mar 05, 2020 01:42:49 PM IST  platform: Windows NT

import sys
from PIL import Image, ImageTk

import home_window_support
import os.path

import department_window
import department_window_support
import screening_camp_window
import screening_camp_window_support
import turnover_window
import turnover_window_support
import satelite_window
import satelite_window_support
import view_data_window_support

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True



def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = View_Data (root)
    view_data_window_support.init(root, top)
    root.mainloop()

w = None
def create_View_Data(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = View_Data (w)
    view_data_window_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_View_Data():
    global w
    w.destroy()
    w = None

class View_Data:
    def __init__(self, View_Data_Window=None):
        '''This class configures and populates the toplevel window.
                   Department_Window is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font10 = "-family {Courier New} -size 10 -weight normal -slant" \
                 " roman -underline 0 -overstrike 0"
        font11 = "-family {Helvatica} -size 13 -weight normal -slant " \
                 "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant " \
                "roman -underline 0 -overstrike 0"

        self.style = ttk.Style()
        # self.data = Database("dental.db")
        if sys.platform == "win32":
            self.style.theme_use('winnative')
            self.style.configure('.', background=_bgcolor)
            self.style.configure('.', foreground=_fgcolor)
            self.style.map('.', background=
            [('selected', _compcolor), ('active', _ana2color)])

        View_Data_Window.geometry("1491x764+35+31")
        View_Data_Window.minsize(148, 1)
        View_Data_Window.maxsize(1924, 1055)
        View_Data_Window.resizable(1, 1)
        View_Data_Window.title("VIEW DATA")
        View_Data_Window.configure(background="#40b3a2")

if __name__ == '__main__':
    vp_start_gui()





